POST http://localhost:3003/organization/register 
Content-Type: application/json

{
    "name": "kajoma" 
}

###

GET http://localhost:3003/organization/list 
Content-Type: application/json

###

GET http://localhost:3003/organization/list/2 
Content-Type: application/json

###

GET http://localhost:3003/organization/97593fe3-8b6c-4657-962c-af7da1c9d50d
Content-Type: application/json

###

POST http://localhost:3003/user/register 
Content-Type: application/json

{
    "name": "marvin",
    "email": "marvin@gmail.com" 
}

###

GET http://localhost:3003/user/list 
Content-Type: application/json

###

GET http://localhost:3003/user/list/2 
Content-Type: application/json

###

GET http://localhost:3003/user/f0170114-e5e6-4364-b1d7-9843844fa0d8
Content-Type: application/json

###

GET http://localhost:3003/membership/list/puma?page=2
Content-Type: application/json

###

POST http://localhost:3003/membership/register
Content-Type: application/json

{
    "email": "marvin@gmail.com",
    "organization": "puma",
    "role": "marketing" 
}


